### ISSUE TITLE
Error executing task

### ISSUE THREAD

**Issue by darkrouille** [BeardlessBrady/Currency-Mod#111]
please help me every time i open a my game crash wallet on my server 

[02:28:06] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_242]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_242]
at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
at net.minecraftforge.items.ItemStackHandler.deserializeNBT(ItemStackHandler.java:196) ~[ItemStackHandler.class:?]
at gunn.modcurrency.mod.container.util.INBTInventory.readInventoryTag(INBTInventory.java:18) ~[INBTInventory.class:?]
at gunn.modcurrency.mod.container.ContainerWallet.didInventorySizeChange(ContainerWallet.java:195) ~[ContainerWallet.class:?]
at gunn.modcurrency.mod.container.ContainerWallet.<init>(ContainerWallet.java:59) ~[ContainerWallet.class:?]
at gunn.modcurrency.mod.handler.GuiHandler.getServerGuiElement(GuiHandler.java:48) ~[GuiHandler.class:?]
at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:253) ~[NetworkRegistry.class:?]
at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:88) ~[FMLNetworkHandler.class:?]
at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
at gunn.modcurrency.mod.item.ItemWallet.openGui(ItemWallet.java:49) ~[ItemWallet.class:?]
at gunn.modcurrency.mod.item.ItemWallet.func_77659_a(ItemWallet.java:54) ~[ItemWallet.class:?]
at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[aip.class:?]
at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:358) ~[or.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:765) ~[pa.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[mb.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[mb.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_242]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_242]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
... 5 more
> [02:28:16] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: NutellNute lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
[02:28:16] [Server thread/INFO] [minecraft/DedicatedServer]: NutellNute left the game

**Comment by Beardlessbrady** [comment]
Unfortunately I am only supporting the 2.0 version. Sorry
