### ISSUE TITLE
[issue] client closes when trying to put money as funds in exchange machine

### ISSUE THREAD

**Issue by winsrp** [BeardlessBrady/Currency-Mod#13]
Only item in exchange machine is full health stone sword, set for 5$, when the user tries to enter the funds on the corner, crash!

[15:02:04] [Client thread/INFO] [STDOUT/]: [net.minecraft.init.Bootstrap:func_179870_a:560]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (SpiceOfLife AppleCore-mc1.10.2-2.1.0.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 12/30/16 3:02 PM
Description: Rendering screen

java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.set(Unknown Source)
	at gunn.modcurrency.client.guis.GuiBuySell.drawIcons(GuiBuySell.java:207)
	at gunn.modcurrency.client.guis.GuiBuySell.func_146979_b(GuiBuySell.java:120)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:114)
	at gunn.modcurrency.client.guis.GuiBuySell.func_73863_a(GuiBuySell.java:89)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:332)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1400)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.set(Unknown Source)
	at gunn.modcurrency.client.guis.GuiBuySell.drawIcons(GuiBuySell.java:207)
	at gunn.modcurrency.client.guis.GuiBuySell.func_146979_b(GuiBuySell.java:120)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:114)
	at gunn.modcurrency.client.guis.GuiBuySell.func_73863_a(GuiBuySell.java:89)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:332)

-- Screen render details --
Details:
	Screen name: gunn.modcurrency.client.guis.GuiBuySell
	Mouse location: Scaled: (416, 77). Absolute: (833, 550)
	Screen size: Scaled: (683, 353). Absolute: (1366, 705). Scale factor of 2

**Comment by Beardlessbrady** [comment]
Cant seem to recreate the issue. What mods do you have present, can you recreate it?

**Comment by BeardlessBrady** [comment]
?

**Comment by BeardlessBrady** [comment]
K Then

**Comment by winsrp** [comment]
sorry, u know, holidays, kind of hard to keep up on the computer.

We have:

Architecture craft
biomes o plenty
currency... obviously
advanced generators
grave stone mod
immersive engineering
iron backpacks
journeymap
Minecraft comes alive
preasure pipes
progressive automation
rftools, dimensions, controls, deepresonance, the one prove (all from mcjty)
fast leaf decay
geographicraft
recurrent complex
rouguelike dungeons
roughmobs
special ai
spice of life
storage network
tinkers construct

(+ all libraries to make things work)

**Comment by Beardlessbrady** [comment]
Omg so sorry. There was this one user who put a ton of issue reports today, for some reason I missread this one as him, didn't mean to be impatient.

**Comment by Beardlessbrady** [comment]
Ill look into it soon

**Comment by Beardlessbrady** [comment]
Are you able to recreate the issue or was it a one time thing? I'm unable to recreate it even with the mods.

**Comment by winsrp** [comment]
sure don't worry, lol. Well I cannot replicate it in my computer, but the user can make the dump happen every time, he is running on limited memory, 1200M for java assigment since he really doesn't have much ram (already doing miracles with that amount of RAM), not sure if that has something to do about it.

**Comment by Beardlessbrady** [comment]
hmm that is odd that its user specific, I understand the issue just not why its happening. unsure what to do.

**Comment by Beardlessbrady** [comment]
I may have fixed the issue, ask them to try the newest version
