### ISSUE TITLE
Crashing on Foolcraft running the Currency Mod

### ISSUE THREAD

**Issue by TheonlyTazz** [BeardlessBrady/Currency-Mod#25]
```
-- Head --
Thread: Client thread
Stacktrace:
	at gunn.modcurrency.mod.tiles.TileSeller.setItemAmount(TileSeller.java:564)
	at gunn.modcurrency.mod.containers.ContainerBuySell.func_184996_a(ContainerBuySell.java:218)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:557)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:627)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_184098_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:15)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:522)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:389)
	at gunn.modcurrency.mod.guis.GuiBuySell.func_73864_a(GuiBuySell.java:447)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)

-- Affected screen --
Details:
	Screen name: gunn.modcurrency.mod.guis.GuiBuySell`

```

so you crash as soon as you click on anything in the gui's on a multiplayer server.

i hope this gets fixed as we are wanting to use this as a shopping currency for our server

-Tazz

**Comment by Beardlessbrady** [comment]
I will look into it in the next day or so

**Comment by Beardlessbrady** [comment]
Alright should be fixed in the next update coming in a week or 2 at most.
