### ISSUE TITLE
Renamed Wallet crash 1.12.2

### ISSUE THREAD

**Issue by Haerar** [BeardlessBrady/Currency-Mod#92]
Hi Brady,
Not an essential error but would be nice for it to be fixed so we can have named wallets - or if there's any other way to name them let me know. Crafted a wallet and renamed it to "Haerar's Wallet" via anvil; but on right clicking with it in my hand the game simply CTD's - top of stacktrace below. Wallet works fine if not renamed via anvil.

`---- Minecraft Crash Report ----

WARNING: coremods are present: *snip*
at net.minecraftforge.items.ItemStackHandler.deserializeNBT(ItemStackHandler.java:196)
	at gunn.modcurrency.mod.container.util.INBTInventory.readInventoryTag(INBTInventory.java:18)
	at gunn.modcurrency.mod.container.ContainerWallet.didInventorySizeChange(ContainerWallet.java:195)
	at gunn.modcurrency.mod.container.ContainerWallet.<init>(ContainerWallet.java:59)
	at gunn.modcurrency.mod.client.gui.GuiWallet.<init>(GuiWallet.java:38)
	at gunn.modcurrency.mod.handler.GuiHandler.getClientGuiElement(GuiHandler.java:74)
	at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:276)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:111)
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550)
	at gunn.modcurrency.mod.item.ItemWallet.openGui(ItemWallet.java:49)`

**Comment by Beardlessbrady** [comment]
Ah, yea I see how that error occurs. I wont fix it for the 1.0 version as Im focusing on 2.0 release BUT I will make sure this error does not occur on the 2.0 edition. Thanks for bringing this up.

Just for reference this error has to do with me comparing DISPLAY NAMES of an item not ITEM NAMES. SO silly of me
